---
# tasks file for reporting
- block:
    - name: Generating Patching report
      ansible.builtin.template:
        src: reports.j2
        dest: "/var/www/html/patching_reports/patch_report_{{ inventory_hostname }}_{{ ansible_date_time.date }}.html"
    - name: Generating Service report
      ansible.builtin.template:
        src: service.j2
        dest: "/var/www/html/service_reports/service_status_{{ inventory_hostname }}_{{ ansible_date_time.date }}.html"
  notify: Restarting apache2 service